services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - odoo_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  odoo:
    image: odoo:18.0
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo_data:/var/lib/odoo
    networks:
      - odoo_network
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  db_data:
  odoo_data:

networks:
  odoo_network:
    driver: overlay
